image: node

variables:
  PCF_API: api.system.pcf-ext.testservicensw.net
  PCF_ORG: FFactory
  PCF_SPACE: formio-viewer
  SHA: ${CI_COMMIT_SHA:0:8}

before_script:
  - curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx

cache:
  paths:
    - /node_modules/

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir -p ./public
    - cp ./README.md ./public/
  artifacts:
    paths:
      - public
  only:
    - dev

deploy_dev:
  stage: deploy
  environment:
    name: Dev
    url: https://formio.apps.pcf-ext.testservicensw.net
  variables:
    PCF_SPACE: formio-viewer
    BUILD_ENV: dev
    DEPLOY_ENV: DEV
  script:
    - ./cf login -a ${PCF_API} -u ${PCF_USERNAME} -p ${PCF_PASSWORD} -o ${PCF_ORG} -s ${PCF_SPACE}
    - ./cf push --var deploy_env=${DEPLOY_ENV} --var build_env=${BUILD_ENV}
  only:
    - master
